export default {
  100: 'XML parsing error.',
  101: 'VAST schema validation error.',
  102: 'VAST version of response not supported.',
  200: 'Trafficking error.',
  201: 'Video player expecting different linearity.',
  202: 'Video player expecting different duration.',
  203: 'Video player expecting different size.',
  300: 'General Wrapper error.',
  301: 'Timeout.',
  302: 'Wrapper limit reached.',
  303: 'No Ads VAST response after one or more Wrappers.',
  400: 'General Linear error.',
  401: 'File not found.',
  402: 'Timeout of MediaFile URI.',
  403: 'No supported MediaFile found.',
  405: 'Problem displaying MediaFile.',
  500: 'General NonLinearAds error.',
  501: 'Unable to display NonLinear Ad because creative dimensions do not align with creative display area.',
  502: 'Unable to fetch NonLinearAds/NonLinear resource.',
  503: 'Couldn\'t find NonLinear resource with supported type.',
  600: 'General CompanionAds error.',
  601: 'Unable to display Companion because creative dimensions do not fit within Companion display area.',
  602: 'Unable to display Required Companion.',
  603: 'Unable to fetch CompanionAds/Companion resource.',
  604: 'Couldn\'t find Companion resource with supported type.',
  900: 'Undefined error.',
  901: 'General VPAID error.'
}
